daftar/urls.py
from django.urls import path
from . import views 

app_name = 'daftar'

urlpatterns = [
    path('', views.daftar, name='daftar')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('ganti_warna', views.ganti_warna, name='ganti_warna'),
    path('keluar', views.keluar, name='keluar'),
]

masuk/urls.py
from django.urls import path
from . import views

app_name = 'masuk'

urlpatterns = [
    path('', views.masuk, name='masuk')
]

ppwstory9/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('masuk/', include('masuk.urls')),
    path('daftar/', include('daftar.urls')),
]

daftar/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User

class LatarBelakang(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    warna = models.CharField(max_length=7, default="#FFF500")
    

masuk/models.py
from django.db import models

# Create your models here.

daftar/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class DaftarForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password1']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = "Nama Pengguna"
        self.fields['password1'].label = "Kata Sandi"
        del self.fields['password2']

masuk/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm

class MasukForm(AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = "Nama Pengguna"
        self.fields['password'].label = "Kata Sandi"

daftar/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from main.models import LatarBelakang
from django.contrib.auth import authenticate, login
from .forms import DaftarForm

def daftar(request):
    context = {}
    if request.method == 'GET':
        empty_form = DaftarForm()
        context['form'] = empty_form
    elif request.method == 'POST':
        filled_form = DaftarForm(request.POST)
        if filled_form.is_valid():
            username = request.POST['username']
            password = request.POST['password1']
            
            new_user = User.objects.create_user(username=username, password=password)
            LatarBelakang.objects.create(user=new_user)
            login_user = authenticate(request, username=username, password=password)
            login(request, login_user)
            
            return HttpResponseRedirect(reverse('main:home'))
        else:
            context['form'] = filled_form
    return render(request, 'daftar/daftar.html', context)

main/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .models import LatarBelakang

def home(request):
    context = {}

    user = request.user
    if user.is_authenticated:
        context['user_color'] = LatarBelakang.objects.get(user=user).warna
    else:
        context['user_color'] = "#FFF500";
    
    return render(request, 'main/home.html', context)

@login_required
def ganti_warna(request):
    if request.GET.get("new_color", False):
        changed_background = LatarBelakang.objects.get(user=request.user)
        changed_background.warna = request.GET["new_color"]
        changed_background.save()
    return HttpResponseRedirect(reverse('main:home'))
    
def keluar(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:home'))

masuk/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login
from .forms import MasukForm

def masuk(request):
    context = {}
    if request.method == 'GET':
        empty_form = MasukForm()
        context['form'] = empty_form
    elif request.method == 'POST':
        filled_form = MasukForm(data=request.POST)
        if filled_form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            
            login_user = authenticate(request, username=username, password=password)
            
            if login_user is not None:
                login(request, login_user)
                if request.GET.get('next', False):
                    request.GET['next'].replace('%23', '#')
                    return HttpResponseRedirect(request.GET['next'])
                else:
                    return HttpResponseRedirect(reverse('main:home'))
            else:
                print("Akun tidak dikenal")
                context['form'] = filled_form
        else:
            context['form'] = filled_form
    return render(request, 'masuk/masuk.html', context)

daftar/templates/daftar/daftar.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftarkan Akun</title>
<link rel="stylesheet" href="{% static 'daftar/css/style.css' %}">
{% endblock meta %}

{% block content %}
<div id="main-div">
    <form action="" method="POST">
        {% csrf_token %}
        <div id="form-daftar">
            {% for field in form %}
            <div class="form-field">
                <p>{{ field.label }}</p>
                {{ field }}
                {% for error in field.errors %}
                    <div class="form-error">- {{ error }}</div>
                {% endfor %}
            </div>
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="form-error">- {{ error }}</div>
            {% endfor %}
            <button class="my-btn my-submit-btn" type="submit">Daftar</button>
            <div style="text-align: center;"><a class="my-link" href="{% url 'masuk:masuk' %}">Sudah punya akun? Masuk</a></div>
        </div>
    </form>
</div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Selamat Datang</title>
<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'main/js/script.js' %}"></script>
<style>
    body {
        background-color: {{ user_color }};
    }
</style>
{% endblock meta %}

{% block content %}
<div id="main-div">
    {% if user.is_authenticated %}
    <div class="greetings">Halo, {{ user }}</div>
    <div><a class="my-link" href="/keluar">Bukan {{ user }}? Keluar</a></div>
    <div><p style="font-size: large;">Pilih warna</p></div>
    <input id="color-input" type="color" value="{{ user_color }}">
    {% else %}
    <div class="greetings">Selamat datang di</div>
    <div class="greetings"><b>Ganti Latar Belakang</b></div>
    <div>Ganti latar belakang ini sesuai selera Anda!</div>
    <div id="auth">
        <a class="my-btn" href="/masuk">Masuk</a>
        <a class="my-btn" href="/daftar">Daftar</a>
    </div>
    {% endif %}
</div>
{% endblock content %}

masuk/templates/masuk/masuk.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Masuk Akun</title>
<link rel="stylesheet" href="{% static 'masuk/css/style.css' %}">
{% endblock meta %}

{% block content %}
<div id="main-div">
    <form action="" method="POST">
        {% csrf_token %}
        <div id="form-masuk">
            {% for field in form %}
            <div class="form-field">
                <p>{{ field.label }}</p>
                {{ field }}
                {% for error in field.errors %}
                    <div class="form-error">- {{ error }}</div>
                {% endfor %}
            </div>
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="form-error">- {{ error }}</div>
            {% endfor %}
            <button class="my-btn my-submit-btn" type="submit">Masuk</button>
            <div style="text-align: center;"><a class="my-link" href="{% url 'daftar:daftar' %}">Belum punya akun? Daftar</a></div>
        </div>
    </form>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"-->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="icon" href="{% static 'img/apa-ini.png' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>